config/routes.rb
Workflow::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #root :to => 'high_voltage/pages#show', :id => 'welcome'
  root :to => 'projects#index'

  resources :projects do
  	resources :steps do
  		get 'finish', :on => :member
  		get 'content', :on => :member

  		resources :items do
        get 'check', :on => :member
        get 'uncheck', :on => :member
      end
  	end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :step
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :steps
	validates :title, :presence =>  { :message => "不可空白" }
	after_create :default_steps

	belongs_to :owner, :class_name => "User", :foreign_key => :user_id


	def default_steps
		8.times do |n|
			step = steps.build()
			step.no = n+1
			step.name = "Step#{step.no}"
			step.finished = false
			step.save

			3.times do |i|
				item = step.items.build()
				item.summary = "item#{i+1}"
				item.save
			end
		end
	end

	def editable_by?(user)
		user && user == owner
	end
end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/step.rb
class Step < ActiveRecord::Base
	belongs_to :project
	has_many :items
	validates :name, :presence => { :message => "欄位不可空白" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  has_many :projects
  
  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html  {
          authenticate_user!
        }
        format.js{
          render :partial => "common/not_logined"
        }
        format.all {
          head(:unauthorized)
        }
      end
    end
  
  end


  def require_is_admin
    unless (current_user && current_user.admin?)
      redirect_to root_path, :flash => { :error => "no permission" }
    end
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u|
        u.permit(:name, :email, :password, :password_confirmation)
      }
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :login_required, :only => [ :edit, :update, :finished, :checked ]
	before_action :get_project_step_item

	def check
		@item.checked = true;
		@item.save


		done = true
		@item.step.items.each do |i|
			done = false if !i.checked
		end

		respond_to do |format|
			format.html { render :json => { success: true, done: done }, :content_type => 'application/json' }
		end
	end

	def uncheck
		@item.checked = false;
		@item.save

		respond_to do |format|
			format.html { render :json => { success: true, done: false }, :content_type => 'application/json' }
		end
	end

	private

	def get_project_step_item
		@project = current_user.projects.find(params[:project_id])
		@step = @project.steps.find(params[:step_id])
		@item = @step.items.find(params[:id])
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :login_required, :only => [:index, :new, :edit, :create, :destroy]
	def index
		@projects = current_user.projects.all
	end

	def new
		@project = Project.new
	end

	def edit
		@project = current_user.projects.find(params[:id])
	end

	def update
		@project = current_user.projects.find(params[:id])
		if @project.update(project_params)
			redirect_to projects_path
		else
			render :edit
		end
	end

	def create
		@project = current_user.projects.build(project_params)
		if @project.save 
			redirect_to projects_path
		else
			render :new
		end
	end

	def destroy
		@project = current_user.projects.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end

	private 

	def project_params
		params.require(:project).permit(:title, :description)
	end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

	before_action :login_required, :only => [ :edit, :update, :finished ]
	before_action :get_project_step

	def edit
		# @project = Project.find(params[:project_id])
		# @step = @project.steps.find(params[:id])
	end

	def update
		# @project = Project.find(params[:project_id])
		# @step = @project.steps.find(params[:id])

		if @step.update(step_params)
			redirect_to projects_path
		else
			render :edit
		end
	end

	def finish
		move_to_this_step(@project, @step)
		redirect_to projects_path
	end

	def content
		respond_to do |format|
			format.html { render :layout => !request.xhr? }
		end
	end

	private

	def get_project_step
		@project = current_user.projects.find(params[:project_id])
		@step = @project.steps.find(params[:id])
	end

	def move_to_this_step(project, step)
		@steps = project.steps
		@steps.each do |s|
			if s.no <= step.no
				s.finished = true
				s.save
			else
				s.finished = false
				s.save
			end
		end
	end

	def step_params
		params.require(:step).permit(:name, :memo)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <%= render_list :class => "nav nav-pills pull-right" do |li|
      #li << link_to( "Link1", "#")
      #li << link_to( "Link2", "#")   
      #li << link_to( "Link3", "#")
      #li << link_to( "Link4", "#")
  end %>
  <p class="copyright">Copyright @2012 <%= Setting.app_name %> All rights reserved.</p>

</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.erb
<div class="navbar navbar-fixed-top ">
      <div class="navbar-inner top ">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to(Setting.app_name, Setting.domain , :class => "brand" )%>

          <%= render :partial => "common/search_form" %>

   
     
          <div class="nav-collapse">
      
              <%= render_list :class => "nav" do |li|
                li << link_to("Link-1","#")
                li << link_to("Link-2","#")
                li << link_to("Link-3","#")
              end %>
              
              <%= render :partial => "common/user_nav"%>

          </div>
    </div>
  </div>

  <%= yield :submenu %>

</div>

app/views/common/_not_logined.js.erb
if (confirm("Please login first, proceed?") )
{
	window.location = "/users/sign_in";
}

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">

    <li>
      <div class="social"> <%=  fb_like(Setting.domain) %>  </div>
    </li>

  <% if current_user %>    

    <li class="dropdown">
      <%= link_to "/account" , :class => "dropdown-toggle", :data => { :toggle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>

      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout",destroy_user_session_path, :method => :delete )
      end %>

    </li>

<% else %>
  <li> <%= link_to( "Sign Up" ,new_user_registration_path) %> </li>
  <li> <%= link_to( "Login", new_user_session_path )  %> </li>   
  <li> <%= link_to( "FB Login", "/users/auth/facebook" )  %> </li>   
<% end %>


</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

<%= render :partial => "common/menu" %>

  <div class="container">

      <%= notice_message %>

      <div class="content">
        <div class="row">
          <%= yield %>
          <%= yield (:sidebar) %>
        </div> 
    
      </div>

      <%= render :partial => "common/footer" %>    
  </div>



  

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>

  <%= yield :javascripts %>


</body>
</html>

app/views/pages/welcome.html.erb
<div class="span12">
	<h1> Welcome </h1>
</div>

app/views/projects/edit.html.erb
<div class="span12">
	<%= simple_form_for @project do |f| %>
		<%= f.input :title, :input_html =>  { :class => "input_xxlarge" } %>
		<%= f.input :description, :input_html => { :class => "input_xxlarge" } %>
		<div class="form-actions">
			<%= f.submit "更新", :disabled_with => "處理中...", :class => "btn btn-primary" %>
			<%= link_to("取消", projects_path, :class => "btn") %>
		</di>
	<% end %>
</div>

app/views/projects/index.html.erb
<div class="span12">
	<h1><%= current_user.name %>工作流程表</h1>
	<div class="projectlist">
		<div class="cmd">
			<%= link_to("建立新專案", new_project_path, :class => "btn btn-mini btn-primary pull-right") %>
		</div>
		<div class="projects">
		<% @projects.each do |project| %>
		<div>
			<%= project.title %>&nbsp;
			<div class="pull-right">
			<% if current_user && project.editable_by?(current_user) %>
			<%= link_to("Delete", project_path(project), :method => :delete, :class => "btn btn-mini", :confirm => "確定要刪除嗎?") %>
			<%= link_to("Edit", edit_project_path(project), :class => "btn btn-mini") %>
			<% end %>
			</div>
		</div>
		<div class="list">
			<div class="container">
			<ol class="progtrckr" data-progtrckr-steps="<%= project.steps.count %>">
			    <% project.steps.each do |step| 
			    %><li class="progtrckr-<%= step.finished ? 'done' : 'todo' %>" data-poload="<%= content_project_step_path(project, step) %>"><%= link_to(step.name, finish_project_step_path(project, step), :confirm => "確定修改到要到這個步驟嗎？", :id => "link-#{project.id}-#{step.id}" )%></li><!--
			 	--><% end %>
			</ol>
			</div>
		</div>
		<% end %>
		</div>
	</div>
</div>
<% content_for :javascripts do %>
<script type="text/javascript">
	//$('.progtrckr li').popover();
	// alert($('*[data-poload]').length);
	//var registered = [];
	$('*[data-poload]').hover(function() {
	    var e=$(this);

	    if(e.attr('poped') == 'true')
	    	return;
	    e.attr('poped', 'true');
	    //e.unbind();
	    $.get(e.data('poload'), { "_": $.now() }, function(d) {
	    	$.each($('*[poped]'), function(i,o) { 
	    		var q = $(o);
	    		//拿掉其他popover 項目
	    		if(q[0] != e[0]) {
		    		q.popover('destroy');
		    		q.removeAttr('poped');
	    		}
	    	});
	        e.popover({content: d, html: true, placement: 'bottom'}).popover('show');
	       	// registered.push(e);
	    });
	});


	$(document).on('click', 'input[type=checkbox]', function(event){
    	//console.log($(this).data('id'));
    	var el = $(this);
    	var path = (el[0].checked) ? el.data('check') : el.data('uncheck');
    	$.get(path, { "_": $.now() }, function(r){ 
    		if(el[0].checked)
    			el.parent().addClass('deleted')
    		else
    			el.parent().removeClass('deleted')
    		if(r.done){
    			if(confirm('已完成所有項目，要標記為完成嗎？'))
    				location.href = $('#'+ el.data('link')).attr('href');
    		}
    	});
	});

	// $('.progtrckr li').popover({ content: function(){  
	// 	var o = $(this);
	// 	$.when(ajaxCall(o.data('poload'))).then(function(o){ alert(o); });
	// 	alert(1);
	// }, trigger:'hover', placement: 'bottom' });


	// function ajaxCall(url){
	// 	var deferred = $.Deferred();   //宣告Deferred物件
	// 	$.get(url, function(d){
	// 		deferred.resolve(d);
	// 	});
	// 	return deferred.promise();
	// }

</script>
<% end %>

app/views/projects/new.html.erb
<div class="span12">
	<%= simple_form_for @project do |f| %>
		<%= f.input :title , :input_html => { class: "input_xxlarge" } %>
		<%= f.input :description, :input_html => { class: "input_xxlarge"} %>

		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => "Submiting...", :class => "btn btn-primary" %>
		</div>
	<% end %>
</div>

app/views/steps/content.html.erb
<div class="item-list">
<% @step.items.each do |i| %>
	<div class="item <%= "deleted" if i.checked %>">
	<input type="checkbox" id="item<%= i.id %>" data-check="<%= check_project_step_item_path(@project, @step, i) %>" data-uncheck="<%= uncheck_project_step_item_path(@project, @step, i) %>" data-link="<%= "link-#{@project.id}-#{@step.id}"  %>" <%= "checked" if i.checked %>/><label for="item<%= i.id %>"><%= i.summary %></label>
	</div>
<% end %>
</div>

app/views/steps/edit.html.erb
<div class="span12">
	<%= simple_form_for [@project, @step] do |f| %>
		<%= f.input :name, :input_html => { :class => "input_xxlarge" } %>
		<%= f.input :memo, :input_html => { :class => "input_xxlarge"} %>
		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => "Submiting...", :class => "btn btn-primary" %>
			<%= link_to("Cancel", projects_path, :class=> "btn") %>
		</div>
	<% end %>
</div>